global:
  scrape_interval: 30s

scrape_configs:

  - job_name: 'node'
    static_configs:
      - targets: ['127.0.0.1:9100']

  - job_name: 'speedtest'
    metrics_path: /metrics
    scrape_interval: 60m
    scrape_timeout: 60s  # running speedtest needs time to complete
    static_configs:
      - targets: ['127.0.0.1:9798']

  - job_name: 'ping'
    metrics_path: /probe
    scrape_interval: 60s
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    file_sd_configs:
      - files:
          - pinghosts.yaml
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*);(.*)'  # first is the url, thus unique for instance
        target_label: instance
        replacement: $1
      - source_labels: [__address__]
        regex: '(.*);(.*)'  # second is humanname to use in charts
        target_label: humanname
        replacement: $2
      - source_labels: [instance]
        target_label: __param_target
      - target_label: __address__
        replacement: 127.0.0.1:9115  # The blackbox exporter's real hostname:port.
